#!/bin/sh
#
# Starts pressure sniffer main application.
#

start() {
	printf "Starting pressure_sniffer: "
	/oem/pressure_sniffer -platform linuxfb:fb=/dev/fb0 &

	echo "OK"
}
stop() {
	printf "Stopping pressure_sniffer: "
	killall /oem/pressure_sniffer

	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

